HomeEdu/HomeEdu.UI/Controllers/CourseDetailController.cs
using HomeEdu.Core.Entities;
using HomeEdu.DataAccess.Context;
using HomeEdu.UI.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using static HomeEdu.UI.Helpers.Utilities.AppUserRole;

namespace HomeEdu.UI.Controllers
{
    public class CourseDetailController : Controller
    {
        private readonly AppDbContext _context;

        public CourseDetailController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index(int id)
        {
            var courseDetailVMs = await _context.Courses
                .Include(c => c.CourseDetail)
                .Include(c => c.CourseCatagory)
                .Where(c => c.Id == id)
                .Select(c => new CouseDetailViewModel
                {
                    Blogs = _context.Blogs.Include(B => B.BlogCatagory).ToList(),
                    Course = c,
                    CourseDetail = c.CourseDetail,
                    CourseCatagory = c.CourseCatagory,
                    Assesments = _context.Assesments.FirstOrDefault(a => a.CourseDetailId == c.CourseDetail.Id),
                    SkillLevel = _context.SkillLevels.FirstOrDefault(s => s.CourseDetailId == c.CourseDetail.Id),
                    Language = _context.Languages.FirstOrDefault(l => l.CourseDetailId == c.CourseDetail.Id),
                })
                .ToListAsync();
            if (courseDetailVMs == null)
            {
                return NotFound();
            }
            foreach (var courseDetailVM in courseDetailVMs)
            {
                if (courseDetailVM.Assesments == null)
                {
                    courseDetailVM.Assesments = new Assesments();
                }
                if (courseDetailVM.SkillLevel == null)
                {
                    courseDetailVM.SkillLevel = new SkillLevel();
                }
                if (courseDetailVM.Language == null)
                {
                    courseDetailVM.Language = new Language();
                }
            }
            ViewBag.Courses = await _context.CourseCatagories.ToListAsync();
            return View(courseDetailVMs.FirstOrDefault());
        }

    }
}

HomeEdu/HomeEdu.UI/Controllers/EventDetailController.cs
using HomeEdu.DataAccess.Context;
using HomeEdu.UI.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using static HomeEdu.UI.Helpers.Utilities.AppUserRole;

namespace HomeEdu.UI.Controllers
{
    public class EventDetailController : Controller
    {
        private readonly AppDbContext _context;

        public EventDetailController(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(int Id)
        {
            var Blogs = await _context.Blogs.ToListAsync();
            var @event = await _context.Events.FindAsync(Id);
            var eventDetails = await _context.EventDetails
                .Where(e => e.EventId == Id)
                .ToListAsync();
            var speakers = await _context.Speakers
       .Include(s => s.EventDetail)
       .Where(s => s.EventDetail.EventId == Id)
       .ToListAsync();

            var eventDetailVM = new EventDetailViewModel
            {
                Event = @event,
                eventDetails = eventDetails,
                 Speakers = speakers,
                 Blog= Blogs
            };

            return View(eventDetailVM);
        }
    }
}

HomeEdu/HomeEdu.UI/Controllers/HomeController.cs
using HomeEdu.Core.Entities;
using HomeEdu.DataAccess.Context;
using HomeEdu.UI.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HomeEdu.UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly AppDbContext _context;

        public HomeController(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            HomeVM homeVM = new()
            {
                Blogs = await _context.Blogs.ToListAsync(),
                sliders = await _context.Sliders.ToListAsync(),
                testimonials = await _context.testimonials.ToListAsync(),
                Courses = await _context.Courses.ToListAsync(),
                noticeBoards = await _context.noticeBoards.ToListAsync(),
                events = await _context.Events.ToListAsync()
            };
            return View(homeVM);
        }
    }
}

HomeEdu/HomeEdu.UI/Views/Home/Index.cshtml
@using HomeEdu.Core.Entities;
@using HomeEdu.UI.Helpers.Slash;
@{
    ViewData["Title"] = "Index";
    var count = 1;
    var countEvents = 1;
}
@model HomeVM

<!-- Background Area Start -->
<section id="slider-container" class="slider-area">
    <div class="slider-owl owl-theme owl-carousel">
        <!-- Start Slingle Slide -->
        @foreach (var slider in Model.sliders)
        {
            var imagePath = SlashHelper.ConvertBackslashToSlash(slider.ImagePath);
            <div class="single-slide item" style="background-image:url(@imagePath)">
                <!-- Start Slider Content -->
                <div class="slider-content-area">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-7 col-md-offset-left-5">
                                <div class="slide-content-wrapper">
                                    <div class="slide-content">
                                        <h2>@slider.Title</h2>
                                        <p>@slider.Description</p>
                                        <a class="default-btn" href="about.html">Learn more</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Start Slider Content -->
            </div>
        }
        <!-- End Slingle Slide -->
    </div>
</section>
<!-- Background Area End -->
<!-- Notice Start -->
<section class="notice-area pt-150 pb-150">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="notice-left">
                    <h3>notice board</h3>
                    @foreach (var noticeBoard in Model.noticeBoards.OrderByDescending(b => b.Time).Take(10))
                    {
                        <div class="single-notice-left  @(count % 3 == 0 ? " pb-75": "mb-25 pb-25")">
                            <h4>@noticeBoard.Time.ToString("dd MMMM, yyyy")</h4>
                            <p>@noticeBoard.Detail </p>
                        </div>
                        count++;
                    }
                </div>
            </div>
            <div class="col-md-6">
                <div class="notice-right">
                    <div class="single-notice-right mb-25 pb-25">
                        <h3>PROFESSIONAL TEACHER</h3>
                        <p>I must explain to you how all this mistaken idea of denouncing pleure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings </p>
                    </div>
                    <div class="single-notice-right mb-25 pb-25">
                        <h3>Online courses</h3>
                        <p>I must explain to you how all this mistaken idea of denouncing pleure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings </p>
                    </div>
                    <div class="single-notice-right">
                        <h3>easy to addmission</h3>
                        <p>I must explain to you how all this mistaken idea of denouncing pleure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Notice End -->
<!-- Choose Start -->
<section class="choose-area pb-85 pt-77">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-left-4">
                <div class="choose-content text-start">
                    <h2>WHY YOU CHOOSE EDUHOME ?</h2>
                    <p>I must explain to you how all this mistaken idea of denouncing pleure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings  the master-builder of humanit happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because. </p>
                    <p class="choose-option">I must explain to you how all this mistaken idea of denouncing pleure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings  the master-builder. </p>
                    <a class="default-btn" href="course-details.html">view courses</a>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Choose Area End -->
<!-- Courses Area Start -->
<div class="courses-area pt-150 text-center">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="section-title">
                    <img src="~/assets/img/icon/section.png" alt="section-title">
                    <h2>COURSES WE OFFER</h2>
                </div>
            </div>
        </div>
        <div class="row">

            @foreach (var item in Model.Courses.OrderByDescending(b => b.Id).Take(3))
            {
                <div class="col-lg-4 col-md-6">
                    <div class="single-course">
                        <div class="course-img">
                            <a asp-controller="CourseDetail" asp-action="Index" asp-route-id="@item.Id">
                                <img style="width:100% ;height: 250px;" src="@item.ImagePath" alt="course">
                                <div class="course-hover">
                                    <i class="fa fa-link"></i>
                                </div>
                            </a>
                        </div>
                        <div class="course-content">
                            <h3><a href="course-details.html">@item.Title</a></h3>
                            <p>@item.Description</p>
                            <a class="default-btn" asp-controller="CourseDetail" asp-action="Index" asp-route-id="@item.Id">join now</a>
                        </div>
                    </div>
                </div>
            }

        </div>
    </div>
</div>
<!-- Courses Area End -->
<!-- Event Area Start -->
<div class="event-area one text-center pt-140 pb-150">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="section-title">
                    <img src="~/assets/img/icon/section.png" alt="section-title">
                    <h2>UPCOMMING EVENTS</h2>
                </div>
            </div>
        </div>
        <div class="row">
            @foreach (var Event in Model.events)
            {
                <div class="col-lg-6  @(countEvents < 5 ? "pt-5 pt-lg-0": "pt-5 pt-lg-0")">
                    <div class="single-event mb-35 ">

                        <div class="event-date">
                            <h3><a href="event-details.html">@Event.StartTime.Day <span>@Event.StartTime.ToString("MMMM")</span></a></h3>
                        </div>
                        <div class="event-content text-start " style=" @(countEvents == 2 ? "padding: 18px 0;" : " ") ">
                            <div class="event-content-left">
                                <h4><a href="event-details.html">@Event.Title</a></h4>
                                <ul>
                                    <li><i class="fa fa-clock-o"></i>@Event.StartTime.ToString("hh:mm tt") - @Event.EndTime.ToString("hh:mm tt")</li>
                                    <li><i class="fa fa-map-marker"></i>@Event.Location</li>
                                </ul>
                            </div>
                            <div class="event-content-right">
                                <a class="default-btn" asp-controller="EventDetail" asp-action="Index" asp-route-id="@Event.Id">join now</a>
                            </div>
                        </div>
                    </div>
                </div>
                countEvents++;
            }
        </div>
    </div>
</div>
<!-- Event Area End -->
<!-- Testimonial Area Start -->
<div class="testimonial-area pt-110 pb-105 text-center">
    <div class="container">
        <div class="row">
            <div class="testimonial-owl owl-theme owl-carousel">
                @foreach (var testimonial in Model.testimonials)
                {
                    <div class="col-lg-8 offset-lg-2">
                        <div class="single-testimonial">
                            <div class="testimonial-info">
                                <div class="testimonial-img">
                                    <img src="@testimonial.ImagePath" alt="testimonial">
                                </div>
                                <div class="testimonial-content">
                                    <p>@testimonial.Description</p>
                                    <h4>@testimonial.Name @testimonial.Surname</h4>
                                    <h5>@testimonial.Position, CSE</h5>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
<!-- Testimonial Area End -->
<!-- Blog Area Start -->
<div class="blog-area pt-150 pb-150">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="section-title text-center">
                    <img src="~/assets/img/icon/section.png" alt="section-title">
                    <h2>LATEST FROM BLOG</h2>
                </div>
            </div>
        </div>
        <div class="row">
            @foreach (var blog in Model.Blogs.OrderByDescending(b => b.PostTime).Take(3))
            {
                <div class="col-lg-4 col-md-6">
                    <div class="single-blog">
                        <div class="blog-img">
                            <a asp-controller="blogdetail" asp-action="Index" asp-route-id="@blog.Id"><img style="width:100% ;height: 250px;" src="@blog.ImagePath" alt="blog"></a>
                            <div class="blog-hover">
                                <a href="blog-details.html"><i class="fa fa-link"></i></a>
                            </div>
                        </div>
                        <div class="blog-content">
                            <div class="blog-top">
                                <p>by @blog.PostedBy / @blog.PostTime.ToString("dd MMMM, yyyy") / <i class="fa fa-comments-o"></i> @blog.CommentCount</p>
                            </div>
                            <div class="blog-bottom">
                                <h2><a asp-controller="blogdetail" asp-action="Index">@blog.Title</a></h2>
                                <a asp-controller="blogdetail" asp-action="Index" asp-route-id="@blog.Id">read more</a>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>
<!-- Blog Area End -->
<!-- Subscribe Start -->
<div class="subscribe-area pt-60 pb-70">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 offset-lg-2">
                <div class="subscribe-content section-title text-center">
                    <h2>subscribe our newsletter</h2>
                    <p>I must explain to you how all this mistaken idea </p>
                </div>
                <div class="newsletter-form mc_embed_signup">
                    <form action="https://devitems.us11.list-manage.com/subscribe/post?u=6bbb9b6f5827bd842d9640c82&amp;id=05d85f18ef" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
                        <div id="mc_embed_signup_scroll" class="mc-form">
                            <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="Enter your e-mail address" required>
                            <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                            <div class="mc-news" aria-hidden="true"><input type="text" name="b_6bbb9b6f5827bd842d9640c82_05d85f18ef" tabindex="-1" value=""></div>
                            <button id="mc-embedded-subscribe" class="default-btn" type="submit" name="subscribe"><span>subscribe</span></button>
                        </div>
                    </form>
                    <!-- mailchimp-alerts Start -->
                    <div class="mailchimp-alerts">
                        <div class="mailchimp-submitting"></div><!-- mailchimp-submitting end -->
                        <div class="mailchimp-success"></div><!-- mailchimp-success end -->
                        <div class="mailchimp-error"></div><!-- mailchimp-error end -->
                    </div>
                    <!-- mailchimp-alerts end -->
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Subscribe End -->