HomeEdu/HomeEdu.UI/Controllers/AboutController.cs
using HomeEdu.Core.Entities;
using HomeEdu.DataAccess.Context;
using HomeEdu.UI.ViewModels;
using HomeEdu.UI.ViewModels.AboutViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace HomeEdu.UI.Controllers
{
    public class AboutController : Controller
    {
        private readonly AppDbContext _context;
        public AboutController(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            AboutVM aboutVM = new()
            {
                testimonials = await _context.testimonials.ToListAsync(),
                noticeBoards = await _context.noticeBoards.ToListAsync(),
                Courses = await _context.Courses.ToListAsync(),
                Teachers = await _context.Teachers.ToListAsync(),
            };
            return View(aboutVM);
        }
    }
}

HomeEdu/HomeEdu.UI/Controllers/BlogsController.cs
using AutoMapper;
using HomeEdu.UI.Areas.Admin.ViewModels.BlogViewModels;
using HomeEdu.Core.Entities;
using HomeEdu.DataAccess.Context;
using HomeEdu.UI.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.AspNetCore.Authorization;
using static HomeEdu.UI.Helpers.Utilities.AppUserRole;

namespace HomeEdu.UI.Controllers
{
    public class BlogsController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IMapper _mapper;
        public BlogsController(AppDbContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }
        public async Task<IActionResult> Index(int CaID,string search,int pg = 1)
        {
            PagesVM pagesVM = new()
            {
                Blogs = await _context.Blogs.ToListAsync(),
                Courses = await _context.Courses.Include(c => c.CourseDetail).ToListAsync(),
                BlogCatagories = await _context.BlogCatagories.ToListAsync(),
            };
            if (pagesVM == null)
            {
                return NotFound();
            }
            const int pageSize = 6;
            if (pg < 1)
                pg = 1;
            int rescCout = pagesVM.Blogs.Count();
            var pager = new Pager(rescCout, pg, pageSize);
            int recSkip = (pg - 1) * pageSize;
            this.ViewBag.pager = pager;
            pagesVM.blgoData = pagesVM.Blogs.Skip(recSkip).Take(pager.PageSize).ToList();
            if (string.IsNullOrEmpty(search))
            {
                if (CaID != 0)
                {
                    var BlogsByCategory = pagesVM.blgoData.Where(c => c.BlogCatagoryId == CaID).ToList();
                    int BlogsByCategoryCount = BlogsByCategory.Count;
                    pager = new Pager(BlogsByCategoryCount, pg, pageSize);
                    recSkip = (pg - 1) * pageSize;
                    pagesVM.blgoData = BlogsByCategory.Skip(recSkip).Take(pager.PageSize).ToList();
                    ViewBag.pager = pager;
                }
                else
                {
                    pagesVM.blgoData = pagesVM.blgoData.Skip(recSkip).Take(pager.PageSize).ToList();
                }

                return View(pagesVM);
            }
            else
            {
                var searchByTitle = pagesVM.blgoData.Where(c => c.Title.ToLower().Contains(search.ToLower())).ToList();
                int searchResultCount = searchByTitle.Count;
                pager = new Pager(searchResultCount, pg, pageSize);
                recSkip = (pg - 1) * pageSize;
                pagesVM.blgoData = searchByTitle.Skip(recSkip).Take(pager.PageSize).ToList();
                ViewBag.pager = pager;
                return View(pagesVM);
            }
        }
    }
}

HomeEdu/HomeEdu.UI/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace HomeEdu.UI.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

HomeEdu/HomeEdu.UI/Controllers/EventsController.cs
using AutoMapper;
using HomeEdu.Core.Entities;
using HomeEdu.DataAccess.Context;
using HomeEdu.UI.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using static HomeEdu.UI.Helpers.Utilities.AppUserRole;

namespace HomeEdu.UI.Controllers
{
    public class EventsController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IMapper _mapper;
        public EventsController(AppDbContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }
        public async Task<IActionResult> Index(string search, int pg = 1)
        {
            PagesVM pagesVM = new()
            {
                Events = await _context.Events.Include(e=>e.EventDetail).ToListAsync(),
                Blogs = await _context.Blogs.Include(b=>b.BlogCatagory).ToListAsync()
            };
            if (pagesVM == null)
            {
                return NotFound();
            }
            const int pageSize = 6;
            if (pg < 1)
                pg = 1;
            int rescCout = pagesVM.Events.Count();
            var pager = new Pager(rescCout, pg, pageSize);
            int recSkip = (pg - 1) * pageSize;
            this.ViewBag.pager = pager;

            pagesVM.EventsData = pagesVM.Events.Skip(recSkip).Take(pager.PageSize).ToList();
            if (string.IsNullOrEmpty(search))
            {
                TempData["InfoMessage"] = "Please Provide Search Value";
                pagesVM.EventsData = pagesVM.EventsData.Skip(recSkip).Take(pager.PageSize).ToList();
                return View(pagesVM);
            }
            else
            {
                var searchByTitle = pagesVM.EventsData.Where(c => c.Title.ToLower().Contains(search.ToLower())).ToList();
                int searchResultCount = searchByTitle.Count;
                pager = new Pager(searchResultCount, pg, pageSize);
                recSkip = (pg - 1) * pageSize;
                pagesVM.EventsData = searchByTitle.Skip(recSkip).Take(pager.PageSize).ToList();
                ViewBag.pager = pager;
                return View(pagesVM);
            }
        }
    }
}

HomeEdu/HomeEdu.UI/Views/Shared/_Layout.cshtml
<!doctype html>
<html class="no-js" lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Eduhome - Educational HTML Template</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="~/assets/img/favicon.png">

    <link rel="stylesheet" href="~/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/css/animate.min.css">
    <link rel="stylesheet" href="~/assets/css/meanmenu.css">
    <link rel="stylesheet" href="~/assets/css/magnific-popup.css">
    <link rel="stylesheet" href="~/assets/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/assets/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/assets/css/et-line-icon.css">
    <link rel="stylesheet" href="~/assets/css/reset.css">
    <link rel="stylesheet" href="~/assets/css/ionicons.min.css">
    <link rel="stylesheet" href="~/assets/css/material-design-iconic-font.min.css">
    <link rel="stylesheet" href="~/assets/css/style.css">
    <link rel="stylesheet" href="~/assets/css/responsive.css">
    <script src="~/assets/js/vendor/modernizr-3.11.2.min.js"></script>
</head>
<body>
    <!--[if lt IE 8]>
        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
    <!-- Header Area Start -->


<!-- Mirrored from htmldemo.net/tm/eduhome/eduhome/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 24 Jun 2023 06:56:44 GMT -->
@await Component.InvokeAsync("Header")
    <!-- Header Area End -->
    @RenderBody()
    <!-- Footer Start -->
    <footer class="footer-area">
        <div class="main-footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4 col-md-6">
                        <div class="single-widget pr-60">
                            <div class="footer-logo pb-25">
                                <a href="index.html"><img src="~/assets/img/logo/footer-logo.png" alt="eduhome"></a>
                            </div>
                            <p>I must explain to you how all this mistaken idea of denoung pleure and praising pain was born and give you a coete account of the system. </p>
                            <div class="footer-social">
                                <ul>
                                    <li><a href="#"><i class="zmdi zmdi-facebook"></i></a></li>
                                    <li><a href="#"><i class="zmdi zmdi-pinterest"></i></a></li>
                                    <li><a href="#"><i class="zmdi zmdi-vimeo"></i></a></li>
                                    <li><a href="#"><i class="zmdi zmdi-twitter"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="single-widget">
                            <h3>information</h3>
                            <ul>
                                <li><a href="#">addmission</a></li>
                                <li><a href="#">Academic Calender</a></li>
                                <li><a href="event.html">Event List</a></li>
                                <li><a href="#">Hostel &amp; Dinning</a></li>
                                <li><a href="#">TimeTable</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-2 col-md-6 pt-4 pt-lg-0">
                        <div class="single-widget">
                            <h3>useful links</h3>
                            <ul>
                                <li><a href="course.html">our courses</a></li>
                                <li><a href="about.html">about us</a></li>
                                <li><a href="teacher.html">teachers &amp; faculty</a></li>
                                <li><a href="#">teams &amp; conditions</a></li>
                                <li><a href="event.html">our events</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 pt-4 pt-lg-0">
                        <div class="single-widget">
                            <h3>get in touch</h3>
                            <p>Your address goes here, Street<br>City, Roadno 785 New York</p>
                            <p>+880  548  986  898  87<br>+880  659  785  658  98</p>
                            <p>info@example.com<br>www.example.com</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-bottom text-center">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <p>Copyright © <a href="#">Eduhome</a> 2022. All Right Reserved</p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer End -->

    <script src="~/assets/js/vendor/jquery-3.6.0.min.js"></script>
    <script src="~/assets/js/vendor/jquery-migrate-3.3.2.min.js"></script>
    <script src="~/assets/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/js/jquery.meanmenu.js"></script>
    <script src="~/assets/js/jquery.magnific-popup.js"></script>
    <script src="~/assets/js/ajax-mail.js"></script>
    <script src="~/assets/js/owl.carousel.min.js"></script>
    <script src="~/assets/js/jquery.mb.YTPlayer.js"></script>
    <script src="~/assets/js/jquery.nicescroll.min.js"></script>
    <script src="~/assets/js/plugins.js"></script>
    <script src="~/assets/js/main.js"></script>
    @RenderSection("Scripts", required: false)
</body>

<!-- Mirrored from htmldemo.net/tm/eduhome/eduhome/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 24 Jun 2023 06:57:08 GMT -->
</html>

HomeEdu/HomeEdu.UI/Views/Shared/_Pagenation.cshtml
@model HomeEdu.Core.Entities.Pager

<div>
    @if (@Model.TotalPages > 0)
    {
        <div class="pagination justify-content-end">
            <ul style="display: flex;gap: 5px;font-size: 20px;">
                @for (var pge = 1; pge <= @Model.EndPages + 2; pge++)
                {
                    <p class="page-item @(pge == @Model.CurrentPage ? "active" : "")">
                        <a class="page-link" asp-controller="@Model" asp-action="Index" asp-route-pg="@pge">@pge</a>
                    </p>
                }
                @if (@Model.CurrentPage < @Model.TotalPages + 2)
                {
                    <li>
                        <a class="page-link" asp-controller="Speaker" asp-action="Index" asp-route-pg="@(@Model.CurrentPage + 1)">Next</a>

                    </li>
                    <li>
                        <a class="page-link" asp-controller="Speaker" asp-action="Index" asp-route-pg="@(@Model.TotalPages)">Last</a>
                    </li>
                }
            </ul>
        </div>
    }
</div>
<style>
    .page-link {
        border-radius: 5px;
    }
</style>

HomeEdu/HomeEdu.UI/Views/Shared/_SeccondLayout.cshtml
<html class="js sizes customelements history pointerevents postmessage postmessage-structuredclones webgl websockets cssanimations csscolumns csscolumns-width csscolumns-span csscolumns-fill csscolumns-gap csscolumns-rule csscolumns-rulecolor csscolumns-rulestyle csscolumns-rulewidth csscolumns-breakbefore csscolumns-breakafter csscolumns-breakinside flexbox picture srcset webworkers" lang="en">
<!-- Mirrored from htmldemo.net/tm/eduhome/eduhome/blog-right-side-bar.html by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 24 Jun 2023 06:57:37 GMT -->
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Eduhome - Educational HTML Template</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="/assets/img/favicon.png">

    <link rel="stylesheet" href="/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="/assets/css/animate.min.css">
    <link rel="stylesheet" href="/assets/css/meanmenu.css">
    <link rel="stylesheet" href="/assets/css/magnific-popup.css">
    <link rel="stylesheet" href="/assets/css/owl.carousel.min.css">
    <link rel="stylesheet" href="/assets/css/font-awesome.min.css">
    <link rel="stylesheet" href="/assets/css/et-line-icon.css">
    <link rel="stylesheet" href="/assets/css/reset.css">
    <link rel="stylesheet" href="/assets/css/ionicons.min.css">
    <link rel="stylesheet" href="/assets/css/material-design-iconic-font.min.css">
    <link rel="stylesheet" href="/assets/css/style.css">
    <link rel="stylesheet" href="/assets/css/responsive.css">
    <script src="/assets/js/vendor/modernizr-3.11.2.min.js"></script>
</head>
<body>
    <!--[if lt IE 8]>
        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="/assets/https://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
    <!-- Header Area Start -->
    <header class="top">
        <div class="header-top">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 col-sm-4">
                        <div class="header-top-left">
                            <p>HAVE ANY QUESTION ?  +880 5698  598  6587</p>
                        </div>
                    </div>
                    <div class="col-md-8 col-sm-2">
                        <div class="header-top-right text-md-end text-center">
                            <ul>
                                  @if (User.Identity.IsAuthenticated)
                                {
                                    <li> <a style="color:white">@User.Identity.Name</a></li>
                                    <li><a asp-controller="Auth" asp-action="logout">Log out<i class="bx bx-exit"></i></a></li>
                                }
                                else
                                {
                                <li><a asp-controller="Auth" asp-action="login">login</a></li>
                                }
                                <li><a asp-controller="Auth" asp-action="Register">Register</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="header-area two header-sticky">
            <div class="container">
                <div class="row">
                    <div class="col-md-3 col-sm-5 col-6">
                        <div class="logo">
                            <a href="/assets/index.html"><img src="/assets/img/logo/logo2.png" alt="eduhome"></a>
                        </div>
                    </div>
                    <div class="col-md-9 col-sm-7 col-6">
                        <div class="content-wrapper text-end">
                            <!-- Main Menu Start -->
                            <div class="main-menu">
                                @*main side bar *@
                                <nav style="display: block;">
                                    <ul>
                                        <li>
                                            <a asp-controller="Home" asp-action="Index">Home</a>
                                            @*        <ul>
                                            <li><a href="/assets/index.html">Home One</a></li>
                                            <li><a href="/assets/index-2.html">Home Two</a></li>
                                            <li><a href="/assets/index-3.html">Home Three</a></li>
                                            <li><a href="/assets/index-4.html">Home Four</a></li>
                                            <li><a href="/assets/index-5.html">Home Five</a></li>
                                            </ul>*@
                                        </li>
                                        <li><a asp-controller="About" asp-action="Index">About</a></li>

                                        <li>
                                            <a asp-controller="Courses" asp-action="Index">Course</a>
                                            @*     <ul>
                                            <li><a href="/assets/course.html">courses</a></li>
                                            <li><a href="/assets/course-details.html">courses details</a></li>
                                            </ul>*@
                                        </li>
                                        <li>
                                            <a asp-controller="Events" asp-action="Index">Event</a>
                                        </li>
                                        <li class="hidden-sm">
                                            <a asp-controller="Teachers" asp-action="Index">Teachers</a>
                                            @*        <ul>
                                            <li><a href="/assets/teacher.html">teacher</a></li>
                                            <li><a href="/assets/teacher-details.html">teacher details</a></li>
                                            </ul>*@
                                        </li>
                                        <li>
                                            <a asp-controller="Blogs" asp-action="Index">Blog</a>
                                            @*         <ul>
                                            <li><a href="/assets/blog.html">blog</a></li>
                                            <li><a href="/assets/blog-left-side-bar.html">blog left sidebar</a></li>
                                            <li><a href="/assets/blog-right-side-bar.html">blog righ sidebar</a></li>
                                            <li><a href="/assets/blog-details.html">blog details</a></li>
                                            </ul>*@
                                        </li>
                                        <li> <a asp-controller="Contact" asp-action="Index">Contact</a>
                                        <li>
                                        </li>
                                    </ul>
                                </nav>
                            </div>
                            <!--Search Form Start-->
                            <div class="search-btn">
                                <ul class="header-search search-toggle">
                                    <li class="search-menu">
                                        <i class="fa fa-search"></i>
                                    </li>
                                </ul>
                                <div class="search">
                                    <div class="search-form">
                                        <form id="search-form" method="get" action="#">
                                            <input type="search" placeholder="Search here..." name="search">
                                            <button type="submit">
                                                <span><i class="fa fa-search"></i></span>
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                            <!--End of Search Form-->
                            <!-- Main Menu End -->
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="mobile-menu hidden-sm"></div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- Header Area End -->
    @RenderBody()
    <footer class="footer-area">
        <div class="main-footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4 col-md-6">
                        <div class="single-widget pr-60">
                            <div class="footer-logo pb-25">
                                <a href="/assets/index.html"><img src="/assets/img/logo/footer-logo.png" alt="eduhome"></a>
                            </div>
                            <p>I must explain to you how all this mistaken idea of denoung pleure and praising pain was born and give you a coete account of the system. </p>
                            <div class="footer-social">
                                <ul>
                                    <li><a href="/assets/#"><i class="zmdi zmdi-facebook"></i></a></li>
                                    <li><a href="/assets/#"><i class="zmdi zmdi-pinterest"></i></a></li>
                                    <li><a href="/assets/#"><i class="zmdi zmdi-vimeo"></i></a></li>
                                    <li><a href="/assets/#"><i class="zmdi zmdi-twitter"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="single-widget">
                            <h3>information</h3>
                            <ul>
                                <li><a href="/assets/#">addmission</a></li>
                                <li><a href="/assets/#">Academic Calender</a></li>
                                <li><a href="/assets/event.html">Event List</a></li>
                                <li><a href="/assets/#">Hostel &amp; Dinning</a></li>
                                <li><a href="/assets/#">TimeTable</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-2 col-md-6 pt-4 pt-lg-0">
                        <div class="single-widget">
                            <h3>useful links</h3>
                            <ul>
                                <li><a href="/assets/course.html">our courses</a></li>
                                <li><a href="/assets/about.html">about us</a></li>
                                <li><a href="/assets/teacher.html">teachers &amp; faculty</a></li>
                                <li><a href="/assets/#">teams &amp; conditions</a></li>
                                <li><a href="/assets/event.html">our events</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 pt-4 pt-lg-0">
                        <div class="single-widget">
                            <h3>get in touch</h3>
                            <p>Your address goes here, Street<br>City, Roadno 785 New York</p>
                            <p>+880  548  986  898  87<br>+880  659  785  658  98</p>
                            <p>info@example.com<br>www.example.com</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-bottom text-center">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <p>Copyright © <a href="/assets/#">Eduhome</a> 2022. All Right Reserved</p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer End -->

    <script src="/assets/js/vendor/jquery-3.6.0.min.js"></script>
    <script src="/assets/js/vendor/jquery-migrate-3.3.2.min.js"></script>
    <script src="/assets/js/bootstrap.bundle.min.js"></script>
    <script src="/assets/js/jquery.meanmenu.js"></script>
    <script src="/assets/js/jquery.magnific-popup.js"></script>
    <script src="/assets/js/ajax-mail.js"></script>
    <script src="/assets/js/owl.carousel.min.js"></script>
    <script src="/assets/js/jquery.mb.YTPlayer.js"></script>
    <script src="/assets/js/jquery.nicescroll.min.js"></script>
    <script src="/assets/js/plugins.js"></script>
    <script src="/assets/js/main.js"></script>
    <a id="scrollUp" href="/assets/#top" style="position: fixed; z-index: 2147483647; display: none;"><i class="fa fa-angle-up"></i></a>

    @RenderSection("Scripts", required: false)
</body>

HomeEdu/HomeEdu.UI/Views/Shared/_ValudationScript.cshtml
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.5/jquery.validate.min.js" integrity="sha512-rstIgDs0xPgmG6RX1Aba4KV5cWJbAMcvRCVmglpam9SoHZiUCyQVDdH2LPlxoHtrv17XWblE/V/PP+Tr04hbtA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/4.0.0/jquery.validate.unobtrusive.min.js" integrity="sha512-xq+Vm8jC94ynOikewaQXMEkJIOBp7iArs3IhFWSWdRT3Pq8wFz46p+ZDFAR7kHnSFf+zUv52B3prRYnbDRdgog==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>