HomeEdu/HomeEdu.UI/Controllers/AboutController.cs
using HomeEdu.Core.Entities;
using HomeEdu.DataAccess.Context;
using HomeEdu.UI.ViewModels;
using HomeEdu.UI.ViewModels.AboutViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace HomeEdu.UI.Controllers
{
    public class AboutController : Controller
    {
        private readonly AppDbContext _context;
        public AboutController(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            AboutVM aboutVM = new()
            {
                testimonials = await _context.testimonials.ToListAsync(),
                noticeBoards = await _context.noticeBoards.ToListAsync(),
                Courses = await _context.Courses.ToListAsync(),
                Teachers = await _context.Teachers.ToListAsync(),
            };
            return View(aboutVM);
        }
    }
}

HomeEdu/HomeEdu.UI/Controllers/BlogsController.cs
using AutoMapper;
using HomeEdu.UI.Areas.Admin.ViewModels.BlogViewModels;
using HomeEdu.Core.Entities;
using HomeEdu.DataAccess.Context;
using HomeEdu.UI.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.AspNetCore.Authorization;
using static HomeEdu.UI.Helpers.Utilities.AppUserRole;

namespace HomeEdu.UI.Controllers
{
    public class BlogsController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IMapper _mapper;
        public BlogsController(AppDbContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }
        public async Task<IActionResult> Index(int CaID,string search,int pg = 1)
        {
            PagesVM pagesVM = new()
            {
                Blogs = await _context.Blogs.ToListAsync(),
                Courses = await _context.Courses.Include(c => c.CourseDetail).ToListAsync(),
                BlogCatagories = await _context.BlogCatagories.ToListAsync(),
            };
            if (pagesVM == null)
            {
                return NotFound();
            }
            const int pageSize = 6;
            if (pg < 1)
                pg = 1;
            int rescCout = pagesVM.Blogs.Count();
            var pager = new Pager(rescCout, pg, pageSize);
            int recSkip = (pg - 1) * pageSize;
            this.ViewBag.pager = pager;
            pagesVM.blgoData = pagesVM.Blogs.Skip(recSkip).Take(pager.PageSize).ToList();
            if (string.IsNullOrEmpty(search))
            {
                if (CaID != 0)
                {
                    var BlogsByCategory = pagesVM.blgoData.Where(c => c.BlogCatagoryId == CaID).ToList();
                    int BlogsByCategoryCount = BlogsByCategory.Count;
                    pager = new Pager(BlogsByCategoryCount, pg, pageSize);
                    recSkip = (pg - 1) * pageSize;
                    pagesVM.blgoData = BlogsByCategory.Skip(recSkip).Take(pager.PageSize).ToList();
                    ViewBag.pager = pager;
                }
                else
                {
                    pagesVM.blgoData = pagesVM.blgoData.Skip(recSkip).Take(pager.PageSize).ToList();
                }

                return View(pagesVM);
            }
            else
            {
                var searchByTitle = pagesVM.blgoData.Where(c => c.Title.ToLower().Contains(search.ToLower())).ToList();
                int searchResultCount = searchByTitle.Count;
                pager = new Pager(searchResultCount, pg, pageSize);
                recSkip = (pg - 1) * pageSize;
                pagesVM.blgoData = searchByTitle.Skip(recSkip).Take(pager.PageSize).ToList();
                ViewBag.pager = pager;
                return View(pagesVM);
            }
        }
    }
}

HomeEdu/HomeEdu.UI/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace HomeEdu.UI.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

HomeEdu/HomeEdu.UI/Controllers/CoursesController.cs
using HomeEdu.Core.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using HomeEdu.DataAccess.Context;
using AutoMapper;
using HomeEdu.UI.ViewModels;
using Microsoft.AspNetCore.Authorization;
using static HomeEdu.UI.Helpers.Utilities.AppUserRole;

namespace HomeEdu.UI.Controllers
{
    public class CoursesController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IMapper _mapper;
        public CoursesController(AppDbContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }
        public async Task<IActionResult> Index(int CaID = 0, string search = "", int pg = 1)
        {
            PagesVM pagesVM = new PagesVM()
            {
                Courses = await _context.Courses.ToListAsync(),
                CourseCatagories = await _context.CourseCatagories.ToListAsync(),
                Blogs = await _context.Blogs.ToListAsync()
            };

            if (pagesVM == null)
            {
                return NotFound();
            }

            const int pageSize = 6;

            if (pg < 1)
                pg = 1;

            var filteredCourses = pagesVM.Courses;

            if (!string.IsNullOrEmpty(search))
            {
                filteredCourses = filteredCourses.Where(c => c.Title.ToLower().Contains(search.ToLower()));
            }
            if (CaID != 0)
            {
                filteredCourses = filteredCourses.Where(c => c.CourseCatagoryId == CaID);
            }
            int resCount = filteredCourses.Count();
            var pager = new Pager(resCount, pg, pageSize);
            int recSkip = (pg - 1) * pageSize;
            ViewBag.pager = pager;
            //search by both 
            if (!string.IsNullOrEmpty(search) && CaID != 0)
            {
                pagesVM.Data = filteredCourses.Skip(recSkip).Take(pager.PageSize).Where(C => C.CourseCatagoryId == CaID).ToList();
            }
            pagesVM.Data = filteredCourses.Skip(recSkip).Take(pager.PageSize).ToList();

            return View(pagesVM);
        }


    }
}

HomeEdu/HomeEdu.UI/Views/Shared/Components/Header/Default.cshtml
@model Dictionary<string,string>
<header class="top">
    <div class="header-area header-sticky fixed">
        <div class="container">
            <div class="row">
                <div class="col-md-2">
                    <div class="logo">
                        <a href="index.html"><img src="@Model["MainLogo"]" alt="eduhome" /></a>
                    </div>
                </div>
                <div class="col-md-10">
                    <div class="content-wrapper one">
                        <!-- Main Menu Start -->
                        <div class="main-menu one text-end">
                            <nav>
                                <ul>
                                    <li>
                                    <li><a asp-controller="About" asp-action="Index">About</a></li>
                                    <li>
                                        <a asp-controller="Courses" asp-action="Index">Course</a>

                                            @* <ul>B
                                        <li><a href="course.html">courses</a></li>
                                        you can able to add here some section
                                        <li><a href="course-details.html">courses details</a></li>
                                        </ul>
                                        </li>
                                        *@
                                    <li>
                                        <a asp-controller="events" asp-action="Index">Event</a>
                                    </li>
                                    <li class="hidden-sm">
                                        <a asp-controller="Teachers" asp-action="Index">Teachers</a>
                                                @*    <ul>
                                        <li><a href="teacher.html">teacher</a></li>
                                        <li><a href="teacher-details.html">teacher details</a></li>
                                        </ul>*@
                                    </li>
                                    <li>
                                        <a asp-controller="Blogs" asp-action="Index">Blog</a>
                                                @*  <li><a href="blog.html">blog</a></li>
                                        <ul>
                                        <li><a href="blog-left-side-bar.html">blog left sidebar</a></li>
                                        <li><a href="blog-right-side-bar.html">blog righ sidebar</a></li>
                                        <li><a href="blog-details.html">blog details</a></li>
                                        </ul>
                                        *@
                                    </li>
                                    <li>   <a asp-controller="Contact" asp-action="Index">Contact</a>
                                    <li>
                                        <a asp-controller="auth" asp-action="register">Register</a>
                                                @*  <li><a href="blog.html">blog</a></li>
                                        <ul>
                                        </ul>
                                        *@
                                    </li>
                                    <li>
                                                @if (User.Identity.IsAuthenticated)
                                                {
                                            <a style="color:white">@User.Identity.Name</a>
                                            <ul>
                                                <li>         <a asp-controller="Auth" asp-action="logout">Log out</a><i class="bx bx-exit"></i></li>
                                                <li>         <a asp-controller="Auth" asp-action="ForgotPassword">Reset Password</a><i class="bx bx-exit"></i></li>
                                            </ul>

                                                }
                                                else
                                                {
                                            <a asp-controller="auth" asp-action="login">Login</a>
                                                }
                                    </li>

                                    <li>
                                </ul>
                            </nav>
                        </div>
                        <div class="mobile-menu one"></div>
                        <!-- Main Menu End -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>